Repository kvcops/KV-Nexus, pull requests merged in 2024-10, with the labels that each got.

#27 Created CODE_OF_CONDUCT.md #16
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc-ext, level1, Hacktoberfest, Hacktoberfest-accepted

#42 Update index.html
  LICENSE
  Security.md
  templates/index.html
Labels: enhancement, gssoc-ext, level1, Hacktoberfest, Hacktoberfest-accepted, Assigned

#51 Added scroll to top functionality when logo is clicked in home page
  templates/index.html
Labels: bug, enhancement, gssoc-ext, level1, Hacktoberfest, Hacktoberfest-accepted, Assigned

#12 To adding animation effect on social media icons
  templates/index.html
Labels: enhancement, gssoc-ext, level1, Hacktoberfest-accepted
