Repository kvcops/KV-Nexus, pull requests merged in 2024-11, with the labels that each got.

#100 enhanced analyze page (fixes #96)
  templates/analyze.html
Labels: enhancement, gssoc-ext, level1, Hacktoberfest, Hacktoberfest-accepted, Assigned

#107 Added Contributors page(fixes #98)
  static/contributors.css
  static/contributors.js
  templates/contributors.html
  templates/index.html
Labels: enhancement, gssoc-ext, level2, Hacktoberfest, Hacktoberfest-accepted, Assigned

#108 Fix the Javascript code for the "Contact us Form" #97
  templates/index.html
Labels: bug, enhancement, gssoc-ext, level1, Hacktoberfest, Hacktoberfest-accepted, Assigned

#119 Overlap fix of buttons and cards at Cutting-Edge AI Tools section
  templates/index.html
Labels: enhancement, gssoc-ext, level1, Hacktoberfest, Hacktoberfest-accepted, Assigned
